package com.gmcrypto.suite.common;

public enum ErrorCode {
    ALGORITHM_UNAVAILABLE,
    INVALID_KEY,
    INVALID_PARAMETER,
    SIGNATURE_INVALID,
    ENCRYPTION_FAILED,
    DECRYPTION_FAILED,
    INTEGRITY_CHECK_FAILED,
    REQUEST_EXPIRED,
    REPLAY_DETECTED,
    KEY_NOT_FOUND,
    AUDIT_FAILED
}
